baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Desarrollo Web'
theme = 'hugo-theme-cleanwhite'

[params]
  header_image = "images/foto1.jpg"

  [[params.addtional_menus]]
  title =  "Historia"
  href =  "/historia/"
  [[params.addtional_menus]]
  title =  "Empresas"
  href =  "/empresas/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"

  [params.social]
  github         = "https://github.com/aitkarim1"



[Author]
  name="Karim Ait"

